// generated by unplugin-vue-components
// We suggest you to commit this file into source control
// Read more: https://github.com/vuejs/vue-next/pull/3399

declare module 'vue' {
  export interface GlobalComponents {
    CarbonAccount: typeof import('~icons/carbon/account')['default']
    CarbonDicomOverlay: typeof import('~icons/carbon/dicom-overlay')['default']
    CarbonLogin: typeof import('~icons/carbon/login')['default']
    CarbonMoon: typeof import('~icons/carbon/moon')['default']
    CarbonPassword: typeof import('~icons/carbon/password')['default']
    CarbonSun: typeof import('~icons/carbon/sun')['default']
    CarbonUser: typeof import('~icons/carbon/user')['default']
    MyButton: typeof import('./components/myButton.vue')['default']
  }
}

export { }
